%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"
loopClosing: 1

Camera1.fx: 611.7061
Camera1.fy: 611.9076
Camera1.cx: 320.1767
Camera1.cy: 249.5286

Camera1.k1: 0.13833
Camera1.k2: -0.29287
Camera1.p1: 0.00333
Camera1.p2: 0.00231

# Camera resolution
Camera.width: 640
Camera.height: 480

# Camera frames per second
Camera.fps: 30

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Depth camera baseline * fx (used for depth threshold)
Stereo.ThDepth: 40.0
Stereo.b: 0.0745

# Depth map values factor (D435i depth is in mm)
RGBD.DepthMapFactor: 1000.0

# Transformation from body-frame (imu) to left camera
IMU.T_b_c1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [0.9999808,0.0033242,-0.0052331,0.011367,
         -0.0034123,0.9998513,-0.0168037,0.020342,
         0.0051761,0.0169213,0.9998434,-0.0050164,
         0.0, 0.0, 0.0, 1.0]

# Do not insert KFs when recently lost
IMU.InsertKFsWhenLost: 0

# IMU noise
IMU.NoiseGyro: 2.44e-4
IMU.NoiseAcc: 1.47e-3
IMU.GyroWalk: 1e-4
IMU.AccWalk: 1e-3
IMU.Frequency: 200.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------
ORBextractor.nFeatures: 1250
ORBextractor.scaleFactor: 1.2
ORBextractor.nLevels: 8
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5
Viewer.ViewpointF: 500.0

#--------------------------------------------------------------------------------------------
# Atlas Parameters
#--------------------------------------------------------------------------------------------
System.LoadAtlasFromFile: "/home/a/ros2_ws/src/ORB_SLAM3_ROS2/maps/d435i_map"
System.SaveAtlasToFile: "/home/a/ros2_ws/src/ORB_SLAM3_ROS2/maps/d435i_map"
